### ISSUE TITLE
config file relative paths aren't relative to the config file's parent directory but rather the binary's pwd

### ISSUE THREAD

**Issue by YassinEldeeb** [the-guild-org/conductor#135]
When running `cargo run ../../test_config/config.yaml` while `cd crates/conductor`, and having my `config.yaml` as follows:

```yaml
    plugins:
      - type: persisted_operations
        config:
          store:
            source: file
            path: ./test_config/persisted_operations_store.json
```

It breaks with the error:
```sh
thread 'main' panicked at 'Failed to read file:
Os{ code: 2, kind: NotFound, message: "No such file or directory" }', crates/config/src/serde_utils.rs:22:61
```

Because, it was unable to find the `./test_config/persisted_operations_store.json` path since it started the relative path from the binary's pwd, instead of the config's parent directory, which should be the expected behavior.
