### ISSUE TITLE
Running on CloudFlare Worker WASM doesn't handle GraphiQL

### ISSUE THREAD

**Issue by dotansimha** [the-guild-org/conductor#145]
```yaml
endpoints:
  - path: /graphql
    from: countries
    plugins:
      - type: graphiql
      - type: http_get
```

When accessing through browser, I get an error about invalid GraphQL extraction, and not GraphiQL 😢
