### ISSUE TITLE
Allow to enable/disable each plugin through config

### ISSUE THREAD

**Issue by dotansimha** [the-guild-org/conductor#151]
Related to: https://github.com/the-guild-org/conductor-t2/issues/149

The idea is to allow something like that:
```yaml
plugins:
  - type: graphiql
     enabled: ${GRAPHIQL_ENABLED} 
     config: { ... }
```
