### ISSUE TITLE
Dynamic interpolation of variables

### ISSUE THREAD

**Issue by dotansimha** [the-guild-org/conductor#159]
Not sure where this needs to be implemented. As we might want to allow users to easily do mapping of headers, and other request parameters.

I was thinking of a plugin like this maybe?

```yaml
plugins:
  - type: mapping_transform
     config:
        - from: {request.headers['X-Request-ID']}
          to: {upstreamRequest.headers['X-Request-ID']}
```
