### ISSUE TITLE
Cache core

### ISSUE THREAD

**Issue by dotansimha** [the-guild-org/conductor#206]
I wish to add a top-level `cache` configuration, so we can later use it for implementing plugins and other useful core things. 

For example:

```yaml
caches:
  - type: redis
     id: my-cache
     config:
        connection_string: "..."
```

And then the core of Conductor can use that, or plugins:

```yaml
plugins:
  - type: response_cache 
     config:
        cache: my-cache
```

This way we can also assume that conductor cache is a Key->Value, and users can use a cache that matches their env (D1/KV for CF, Redis/something else for other servers). 

Related:
- https://github.com/the-guild-org/conductor-t2/issues/10
- https://github.com/the-guild-org/conductor-t2/issues/11
