### ISSUE TITLE
New config primitive for handling VRL / primitive values? 🤔 

### ISSUE THREAD

**Issue by dotansimha** [the-guild-org/conductor#222]
We can do something like that: 

```
enum ConfigCondition<Context, Alternative> {
  Primitive(Alternative),
  Condition(Context)
}

struct SomeConfig {
   do_something: Option<ConfigCondition<ConditionContext, bool>>
}
```

In this way we can easily enable configurations like the following:

```yaml
do_something: true
do_something: false # pass primitive value
do_something: "%request.headers.some-header" == "my-value"    # Context will represent the available data on %
```
