### ISSUE TITLE
Support overwriting endpoint GraphQL schema

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/conductor#436]
Allow overwriting of the GraphQL schema used by conductor in front of a GraphQL API.
Introspection and Validation should be done against the `schema` SDL provided, while validated requests should be forwarded to the actual endpoint (requests that contain `__schema` introspection fields and "normal" query selections, must be properly split and re-attached by the conductor). 

**Example Config:**
```yaml
config:
  endpoint: "https://my-source.com/graphql"
  schema: "https://kashdlasdkasjdlkq.eg/schema.graphqls" # THIS IS THE GATEWAY SCHEMA
id: "my-source"
type: "graphql" 
```

**Example Endpoint Schema (`config.endpoint`)**
```graphql
type Query {
  a: Int!
  b: Int!
  foo: String!
}
```

**Example "Schema"/Gateway Schema (`config.schema)`**
```graphql
type Query {
  foo: String!
}
```

--> We only want to expose the `Query.foo` field on the Gateway.

The use case for this is to support schema contracts for single schemas in Hive, see https://github.com/kamilkisiela/graphql-hive/issues/3856
